# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

# Swift dynamic frameworks
use_frameworks!

target 'baseproject' do
    pod 'Alamofire'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Mantle'
    pod 'SnapKit'
    pod 'SDWebImage'
    pod 'TPKeyboardAvoiding'
    pod 'Tweaks'
end